# Generated by Django 3.0.5 on 2020-09-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='slug',
            field=models.SlugField(default='', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(default='', max_length=30, unique=True),
        ),
    ]
