# Generated by Django 3.0.5 on 2020-09-13 15:25

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200913_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=None, max_length=255, null=True, upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=None, max_length=255, null=True, upload_to='blog/articles'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=None, max_length=255, null=True, upload_to='blog/categories'),
        ),
    ]
