# Generated by Django 3.0.5 on 2020-09-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200913_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ('sort_order',), 'permissions': (('manage_blog', 'Manage blog.'),)},
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
