# Generated by Django 3.0.5 on 2020-04-29 15:09

from django.db import migrations, models
import django_measurement.models
import main.core.weight
import measurement.measures.mass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('price', 'Price based shipping'), ('weight', 'Weight based shipping')], max_length=30)),
                ('currency', models.CharField(default='BYN', max_length=3)),
                ('price_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('minimum_order_price_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('maximum_order_price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('minimum_order_weight', django_measurement.models.MeasurementField(blank=True, default=main.core.weight.zero_weight, measurement=measurement.measures.mass.Mass, null=True)),
                ('maximum_order_weight', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass, null=True)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
