# Generated by Django 3.0.7 on 2021-02-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shippingmethod_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'ordering': ('pk',), 'permissions': (('manage_shipping', 'Manage shipping.'),)},
        ),
    ]
