# Generated by Django 3.0.5 on 2020-05-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='base_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
