# Generated by Django 3.0.5 on 2020-06-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200531_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
