# Generated by Django 3.0.5 on 2020-07-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderline_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='review',
        ),
    ]
