# Generated by Django 3.0.5 on 2020-07-04 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderline_review'),
        ('product', '0005_product_maximal_variant_price_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='order_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.OrderLine'),
        ),
    ]
