# Generated by Django 3.0.7 on 2021-02-21 14:58

from django.db import migrations


def update_product_created(apps, schema_editor):
    Product = apps.get_model("product", "Product")
    for p in Product.objects.all():
        p.created_at = p.updated_at
        p.save(update_fields=['created_at'])


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0007_product_created_at'),
    ]

    operations = [migrations.RunPython(update_product_created)
                  ]
