# Generated by Django 3.0.5 on 2020-04-29 15:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('default_weight_unit', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb'), ('oz', 'oz'), ('g', 'g')], default='g', max_length=10)),
                ('default_mail_sender_name', models.CharField(blank=True, default='', max_length=78, validators=[django.core.validators.RegexValidator('[\\n\\r]', code='forbidden_character', inverse_match=True, message='New lines are not allowed.'), django.core.validators.MaxLengthValidator(78)])),
                ('default_mail_sender_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_set_password_url', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Address')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites.Site')),
            ],
            options={
                'permissions': (('manage_settings', 'Manage settings.'),),
            },
        ),
        migrations.CreateModel(
            name='AuthorizationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('facebook', 'Facebook-Oauth2'), ('google-oauth2', 'Google-Oauth2')], max_length=20)),
                ('key', models.TextField()),
                ('password', models.TextField()),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.SiteSettings')),
            ],
            options={
                'unique_together': {('site_settings', 'name')},
            },
        ),
    ]
