# Generated by Django 3.0.5 on 2020-04-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0002_add_default_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='default_weight_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('lb', 'lb'), ('oz', 'oz'), ('g', 'g')], default='kg', max_length=10),
        ),
    ]
